### ISSUE TITLE
README.md needs more info

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/cognicity-reports#1]
The README.md needs more info about what the project is about and how it inter-relates, including hyperlinks to and discussion of submodules.

**Comment by benatwork99** [comment]
FYI as part of the split, I have copied the appropriate parts of the old cognicity-reports-powertrack README in to this one, and added a little technical info on submodules (re. configuration).

**Comment by matthewberryman** [comment]
@benatwork99 thanks for that, I will take a look and if I'm happy I will close the ticket.

**Comment by matthewberryman** [comment]
Partly addressed with a3313ca. In addition, there's a 404 as there's no API for cognicity-reports any more as the docs have moved to be under [cognicity-reports-powertrack](http://cognicity.info/cognicity/api-docs/cognicity-reports-powertrack/index.html) on [cognicity](http://cognicity.info), which needs docs on the master (and linked correctly) and reports submodules. That will have to wait https://github.com/smart-facility/cognicity/issues/4 is fixed.

**Comment by matthewberryman** [comment]
(sorry, still open until https://github.com/smart-facility/cognicity/issues/4 is fixed)

**Comment by tomasholderness** [comment]
Hey @matthewberryman can we close this now? Not sure why it is linked to cognicity#4 above either?

**Comment by tomasholderness** [comment]
Ah, I see because, we're waiting to push docs to the website - but I don't see this happening for v2.0 if we need to rebuild the cognicity page anyway. Thoughts?

**Comment by matthewberryman** [comment]
I think it's now fine - it states there are multiple data sources that are set out in submodules and how to go about enabling different data sources. But we do need to look at describing the architecture at a higher level somewhere else.
