### ISSUE TITLE
Travis build failing to checkout submodules

### ISSUE THREAD

**Issue by benatwork99** [smart-facility/cognicity-reports#3]
This error on Travis:

```
$ git submodule update
Cloning into 'detik'...
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.
Clone of 'git@github.com:smart-facility/cognicity-reports-detik' into submodule path 'detik' failed
```

I guess we need to use a 'deploy key', see http://docs.travis-ci.com/user/private-dependencies/#Using-an-existing-key , to allow Travis to checkout our SSH URL submodules.

Could we use HTTPS URLs for the submodules perhaps?

**Comment by matthewberryman** [comment]
Using https seems to me to be the easiest option of the [various possibilities](http://stackoverflow.com/questions/15674064/github-submodule-access-rights-travis-ci) and also helps anyone cloning it without a GitHub account, so let's do that.

**Comment by benatwork99** [comment]
Travis build is passing with HTTPS URLs.
