### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/cognicity-reports#5]
- Need more documentation on how to activate submodules including how to specify which config file they use.
- PM2 needs to be looked at as well to make sure it is consistent with the new startup process. I think it is.
- If submodules cannot be started up in standalone mode separate from the submodule then raise separate issues there to remove their PM2 processes.json and relevant text from README.md

**Comment by matthewberryman** [comment]
(Note I've just edited the issue so please reload if you've already read it)

**Comment by matthewberryman** [comment]
I have found where the config files are specified, so ignore that first item. I will take a look at PM2, advice on standalone mode / not appreciated.

**Comment by matthewberryman** [comment]
In 033a711 I've tidied up the description to be more explicit about where submodule config lies.

**Comment by tomasholderness** [comment]
Hi Matthew, did you see that submodules are referenced by their folder names in cognicity-reports config.js? As you've already noted, each submodule then has its own local config also. I can add this to documentation when I get chance.

**Comment by matthewberryman** [comment]
Yes I found that bit—I was mainly getting confused about submodule configs, and note I have already updated the documentation in the commit I mentioned in my previous comment.

**Comment by matthewberryman** [comment]
PM2 for cognicity-reports is fine and tested.
For submodules I have updated cognicity-reports-powertrack documentation with https://github.com/smart-facility/cognicity-reports-powertrack/commit/f151a979a6ae8b0bceb438228c3ca9691d233ae5 and @benatwork99 had already removed the processes.json file with https://github.com/smart-facility/cognicity-reports-powertrack/commit/3247f07e3cf79e3ed8a09b83831e3c705651367f (thanks!).
Currently the docs for cognicity-reports-powertrack refer back to docs in 2.0.x of cognicity-reports so it is all consistent but when cognicity-reports 2.0.x is merged back into master then we will need to update, and I have raise a ticket for that: https://github.com/smart-facility/cognicity-reports-powertrack/issues/16

The documentation for cognicity-reports-rem still needs to be written by @benatwork99 so there's nothing to fix there.

I have additionally updated the cognicity-reports docs to refer better to the need to independently run npm (for testing and build) in submodules.
