### ISSUE TITLE
Move all twitter code to cognicity-reports-powertrack (& cognicity-reports-twitter)

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/cognicity-reports#6]
The connection to Twitter should only reside in either the Twitter or the PowerTrack module. Reasoning:
- this error reporting structure not used in practice, with monitoring of AWS systems & logs etc.
- when using PM2 if an error is reported via Twitter- numerous tweets are sent (PM2 restarts execution loop)
- not with fit of new separated architecture as discussed (i.e. future work may see only Detik reports used, for example, in which case user may not have a Twitter account).

**Comment by benatwork99** [comment]
To make sure I'm totally clear, I'm going to:
1. Remove 'send tweet to admin on error' behaviour from cognicity-reports
2. Move all twitter connection code and config from the main cognicity-reports module into the twitter-aware submodules cognicity-reports-powertrack and cognicity-reports-twitter

**Comment by matthewberryman** [comment]
Correct.
